### ISSUE TITLE
come up with a badass icon

### ISSUE THREAD

**Issue by astromme** [tbuckley/brakes#8]
brakes has a great name, now it needs a great icon

**Comment by tbuckley** [comment]
Definitely! The first thing that comes to mind is a disc brake, I always thought they looked cool, and the resemblance to the Chrome icon also seems fitting:
https://images-na.ssl-images-amazon.com/images/I/61glbcx-v8L._SL1000_.jpg

**Comment by astromme** [comment]
![brakes](https://user-images.githubusercontent.com/126986/36082744-115c1370-0f61-11e8-992c-7955221931d5.png)

**Comment by tbuckley** [comment]
![ic_launcher_round](https://user-images.githubusercontent.com/416927/37879255-c827a85a-302a-11e8-8e0f-c903faaf3de7.png)
